


export type ShantenIncrementType = "pair" | "protorun" | "run" | "set";
export type ShantenIncrementTable = {
  [key: string]: ShantenIncrementType[];
};
// melds, pairs, protoRuns
export const shantenIncrementTableFor13TileHand: ShantenIncrementTable = {
  "[4,0,0]": ["pair"],
  "[3,0,0]": ["pair", "protorun"],
  "[3,1,0]": ["pair", "protorun", "set",],
  "[3,0,1]": ["pair", "run"],
  "[3,2,0]": ["set"],
  "[3,1,1]": ["protorun"],
  "[3,0,2]": ["pair", "run"],
  "[2,0,0]": ["pair", "protorun"],
  "[2,1,0]": ["pair", "set", "protorun"],
  "[2,0,1]": ["pair", "protorun", "run"],
  "[2,2,0]": ["pair", "set", "protorun"],
  "[2,1,1]": ["pair", "protorun", "run", "set"],
  "[2,0,2]": ["pair", "protorun"],
  "[2,3,0]": ["set", "protorun"],
  "[2,2,1]": ["set", "run"],
  "[2,1,2]": ["run"],
  "[2,0,3]": ["pair", "run"],
  "[1,0,0]": ["pair", "protorun"],
  "[1,1,0]": ["pair", "protorun", "set"],
  "[1,0,1]": ["pair", "protorun", "run"],
  "[1,2,0]": ["pair", "protorun", "set"],
  "[1,1,1]": ["pair", "protorun", "run", "set"],
  "[1,0,2]": ["pair", "protorun"],
  "[1,3,0]": ["set", "protorun"],
  "[1,2,1]": ["set", "run"],
  "[1,1,2]": ["run"],
  "[1,0,3]": ["pair", "run"],
  "[1,4,0]": ["set"],
  "[1,3,1]": ["set", "protorun"],
  "[1,2,2]": ["set", "run"],
  "[1,1,3]": ["run"],
  "[1,0,4]": ["pair", "run"],
  "[1,5,0]": ["set"],
  "[1,4,1]": ["set", "run"],
  "[1,3,2]": ["set", "run"],
  "[1,2,3]": ["set", "run"],
  "[1,1,4]": ["run"],
  "[1,0,5]": ["pair", "run"],
  "[0,0,0]": ["pair", "protorun"],
  "[0,1,0]": ["pair", "protorun", "set"],
  "[0,0,1]": ["pair", "protorun", "run"],
  "[0,2,0]": ["pair", "protorun", "set"],
  "[0,1,1]": ["pair", "protorun", "run", "set"],
  "[0,0,2]": ["pair", "protorun"],
  "[0,3,0]": ["set", "protorun"],
  "[0,2,1]": ["set", "run"],
  "[0,1,2]": ["run"],
  "[0,0,3]": ["pair", "run"],
  "[0,4,0]": ["set"],
  "[0,3,1]": ["set", "protorun"],
  "[0,2,2]": ["set", "run"],
  "[0,1,3]": ["run"],
  "[0,0,4]": ["pair", "run"],
  "[0,5,0]": ["set"],
  "[0,4,1]": ["set", "run"],
  "[0,3,2]": ["set", "run"],
  "[0,2,3]": ["set", "run"],
  "[0,1,4]": ["run"],
  "[0,0,5]": ["pair", "run"],
  "[0,6,0]": ["set"],
  "[0,5,1]": ["set", "run"],
  "[0,4,2]": ["set", "run"],
  "[0,3,3]": ["set", "run"],
  "[0,2,4]": ["set", "run"],
  "[0,1,5]": ["run"],
  "[0,0,6]": ["pair", "run"],
  undefined: []
};